### ISSUE TITLE
Gear Ratio Incorrect

### ISSUE THREAD

**Issue by TapticDigital** [LeeOtts/Ender3v2-Klipper-Configs#10]
Sprite Extruder Pro has a gear ratio of 3.5:1

**Comment by LeeOtts** [comment]
What makes you say that,  can you link your sources?

**Comment by TapticDigital** [comment]
Sure, it says it a few times on Creality's official Sprite Pro page and
documentation.

https://www.creality3dofficial.com/products/sprite-extruder-direct

**Comment by LeeOtts** [comment]
Thank you for that information. 

Hmm, this is going to require testing. I see a lot of other printer configs that have the same ratio I am using. I guess they got it from the same source. 

Have you tried changing it? How did it work out?

**Comment by TapticDigital** [comment]
I changed it in my klipper settings and noticed marginally better extrusion
steps/accuracy, though I suspect it doesn't make a huge difference

**Comment by LeeOtts** [comment]
Ok cool. Can't wait to give it a try. Thank you for bringing this to my attention. On Dec 23, 2023 1:57 PM, TapticDigital ***@***.***> wrote:
I changed it in my klipper settings and noticed marginally better extrusion

steps/accuracy, though I suspect it doesn't make a huge difference

**Comment by LeeOtts** [comment]
How did you overcome the gear ratio must use 2 units when using 3? 

![gear_ratio_error](https://github.com/LeeOtts/Ender3v2-Klipper-Configs/assets/91760497/8c920209-a7c7-458b-aff4-3c5075f056df)

**Comment by TapticDigital** [comment]
I wasn’t aware there was a 2 digit limit? This is my extruder code: 
`[extruder]
max_extrude_only_distance: 1000.0
step_pin: PB4
dir_pin: PB3
enable_pin: !PC3
microsteps: 16
gear_ratio: 3.5:1
rotation_distance: 7.531
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PA1
…`

so far I haven’t had it give any errors. I’ve also tried just leaving the `gear_ratio` out entirely and saw no difference.

**Comment by LeeOtts** [comment]
Oof, I feel like an idiot. I was doing 3.5.1, not 3.5:1.

**Comment by TapticDigital** [comment]
No worries, full disclosure I know maybe 2% about Klipper, I just noticed an inconsistency when I was trying to figure it out. I am far from knowledgeable about any of this.

**Comment by LeeOtts** [comment]
I definitely had to do some tweaking, but I got the gear ratio corrected to align with Creality specs.  Thank you for bringing this to my attention.
