### ISSUE TITLE
Mesh will not adapt with current CFG files

### ISSUE THREAD

**Issue by basementbuilder17** [LeeOtts/Ender3v2-Klipper-Configs#19]
Would not define the object. I found that I needed to add a line into the start macro "exclude_object_define". Is this intended? Aside from that the rest of it worked really well but that tripped me up. Is it supposed to trigger somewhere else? I also tried adding M117 before the start macro in my slicer and that did not help. 

![image](https://github.com/LeeOtts/Ender3v2-Klipper-Configs/assets/104473685/54f13117-f97a-4c04-b0a8-58bdd2564dad)

![image](https://github.com/LeeOtts/Ender3v2-Klipper-Configs/assets/104473685/55f58bbd-64c1-408e-bc38-887d76ac4b1f)

**Comment by LeeOtts** [comment]
Did you install Kamp prior to using my config? The reason I am asking is that is a recent kamp update. It looks like it was added to a commit 5 months ago. My config uses one from longer ago. If you copy all the files as they are I believe it should work.
