### ISSUE TITLE
[mcu rpi]

### ISSUE THREAD

**Issue by ElTorro5150** [LeeOtts/Ender3v2-Klipper-Configs#3]
First I want to say THANK YOU for your Ender3v2-Klipper-Configs repository. I have an Ender 3v2 with a Sprite Pro and CR Touch installed. I was running a very stable Mainsail OS/Klipper/Klipper Screen setup until someone decided to hit the "Update All" button for me. Long story short, the current Bullseye-based version of Mainsail OS broke everything.

My backups turned out to be corrupt so I was looking at a long painful process of redoing my bed mesh and all of my tweaks. Your repo saved me a lot of time getting back to zero, but I did come across a minor issue with the printer.cfg file.

The line under the header

``[mcu rpi] ``
``serial: /tmp/klipper_host_mcu``  

causes a communication error between Klipper and my Creality 4.2.7 board on bootup. I was going nuts for a few hours trying to figure out why Klippy kept failing to connect. I started going through your printer.cfg file line by line and came across the mcu rpi section. Klippy was failing and logging "Mcu 'rpi': Unable to open port: [Errno 2]" so I thought just maybe that is the issue. I commented it out and BAM everything worked again.

I am by no means a coder. I know very VERY basic things. I think that line works with the input shaper code around it, so I just commented that all out as well. I haven't started messing with shaping yet but it's on my "to learn" list. 

Anyway, I don't think this is a bug per se, but might be worth a note somewhere for future novices.

Sorry for the long-winded message, and thank you again for the work you put into this repo.

**Comment by LeeOtts** [comment]
Hey thanks for the suggestion and sorry for the delay. Just started a new job 2 months ago and have been busy with that.

 I will look into it. 

Have a great day and happy printing!

**Comment by LeeOtts** [comment]
Ok I figured out what is happening. This is from when I had to  set up my accelerometer, and I left that code in the input shaping. I ran into this issue when setting up another Klipper ender on a new pi4 I just got, and it did exactly this. I will fix it. Thank you

**Comment by LeeOtts** [comment]
I have fixed it. 

Thank you so much for raising this issue. You saved me a lot of time tonight setting up another pi.

**Comment by ElTorro5150** [comment]
Thank you for the reply and I'm glad I could help! I plan on setting up an
input shaper soon on my printer I experiment with new software before I
move it to the one I use for grunt work. Like I said in my first email,
your files saved me so much time rebuilding my set up that the very least I
can do is give feedback.


---------------------------------
David A Welch
***@***.***
---------------------------------
