### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by hemna** [LeeOtts/Ender3v2-Klipper-Configs#5]
I'm trying to use your setup for my ender 3v2 v4.2.2 board with the sprite pro extruder and the CRtouch.

In the extruder section of your printer.cfg, why do you have this commented out?

```
#control: pid
#pid_Kp: 23.561
#pid_Ki: 1.208
#pid_Kd: 114.859
```

I can't get klipper to start with that commented out. I just uncommented it to get klipper happy.

Also, you have the following commented out as well in the bltouch section ?

```
[bltouch]
sensor_pin: ^PB1
control_pin: PB0
x_offset: -31.8
y_offset: -40.5
#z_offset: 4
```

**Comment by LeeOtts** [comment]
The pid tuning gets commented out when you do a pid tuning and placed in the Save Config at the very bottom. 

Same with the commented-out z offset. It is put in the Save Config at the bottom when you calibrate a z offset. 

Did you copy the very bottom of the printer config that says Save Config as well?
