### ISSUE TITLE
Work with board 4.2.2?

### ISSUE THREAD

**Issue by marcosasjr** [LeeOtts/Ender3v2-Klipper-Configs#8]
Can use with modified Ender 3 V2 printer, with the Sprite Pro Extruder, CR Touch, but with 4.2.2 board?

Need any changes?

Thx, grate job!

**Comment by LeeOtts** [comment]
They have different pins. So you should be able to take the info from the generic 4.2.2 config file found here, https://github.com/Klipper3d/klipper/blob/master/config/generic-creality-v4.2.10.cfg and plug it into the corresponding pin on this config. So stepper x for you should be

[stepper_x]
step_pin: PC2
dir_pin: !P89
enable_pin: !PC3
microsteps: 16
rotation_distance: 39.87
endstop_pin: ^PA3
position_endstop: 0
position_max: 235
position_min: -15
homing_speed: 50

Now do that with the rest of the config, and you should be up and running.

Let me know if you have any questions or concerns.
